#!/usr/bin/env python3
"""Sample public repositories that were generated by AI app builders.

Uses the GitHub code search API through `gh` to find build markers each
builder leaves behind. Writes one `owner/name` per line.

Usage: python3 research/collect_corpus.py --per-marker 100 > research/corpus.txt
"""
import argparse
import json
import subprocess
import sys

# Build markers each tool leaves in a generated project.
MARKERS = [
    ("lovable", 'lovable-tagger in:file filename:package.json'),
    ("bolt", '"bolt.new" in:file filename:README.md'),
    ("v0", '"v0.dev" in:file filename:README.md'),
]


def gh_code_search(query, per_page, pages):
    repos = []
    for page in range(1, pages + 1):
        try:
            out = subprocess.run(
                ["gh", "api", "-X", "GET", "search/code",
                 "-f", "q=%s" % query,
                 "-f", "per_page=%d" % per_page,
                 "-f", "page=%d" % page],
                capture_output=True, text=True, timeout=60)
            if out.returncode != 0:
                sys.stderr.write("search failed (page %d): %s\n" % (page, out.stderr[:200]))
                break
            data = json.loads(out.stdout)
        except (subprocess.SubprocessError, ValueError) as exc:
            sys.stderr.write("search error: %s\n" % exc)
            break
        items = data.get("items", [])
        if not items:
            break
        for item in items:
            repo = item.get("repository", {})
            if repo.get("fork"):
                continue
            repos.append(repo.get("full_name"))
    return repos


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--per-marker", type=int, default=100)
    args = ap.parse_args()

    seen, out = set(), []
    for name, query in MARKERS:
        per_page = 100
        pages = max(1, args.per_marker // per_page)
        found = gh_code_search(query, per_page, pages)
        kept = 0
        for full in found:
            if not full or full in seen:
                continue
            seen.add(full)
            out.append(full)
            kept += 1
        sys.stderr.write("%-8s %d unique repos\n" % (name, kept))

    for full in out:
        print(full)
    sys.stderr.write("total %d repos\n" % len(out))


if __name__ == "__main__":
    main()
